BRUTEFORCE_LABEL: str = "BruteForce"
BRUTEFORCE_STRATEGY_TAG: str = f"{BRUTEFORCE_LABEL}_strategy"
BRUTEFORCE_ANALYSIS_TAG: str = f"{BRUTEFORCE_LABEL}_analysis"
BRUTEFORCE_FULL_ANALYSIS_TAG: str = f"{BRUTEFORCE_LABEL}_full_analysis"
